name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup R
        uses: r-lib/actions/setup-r@v2

      - name: install dependencies
        run: |
          Rscript -e 'install.packages(c(
            "readxl", "janitor", "dplyr",
            "PRISMAstatement", "yaml", "ggplot2",
            "readr", "tidyr", "robvis"
          ), repos="https://cloud.r-project.org")'

      - name: run analysis scripts
        run: |
          make all

      - name: verify outputs
        run: |
          test -f figures/figure1_prisma_flow.png
          test -f data/processed/included_studies_clean.csv
